cititechd/force-app/main/default/objects/Hiring_Manager__c/Hiring_Manager__c.object-meta.xml
<CustomObject>
    <label>Hiring Manager</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Hiring Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cititechd/force-app/main/default/objects/Hiring_Manager__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

cititechd/force-app/main/default/objects/Hiring_Manager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

cititechd/force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cititechd/force-app/main/default/objects/Position__c/fields/Hiring_Manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring Manager</label>
    <referenceTo>Hiring_Manager__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

cititechd/force-app/main/default/classes/HMTriggerTest.cls
@isTest(seeAllData=false)
private class HMTriggerTest {

 static testMethod void testPost1() {
     Hiring_Manager__c hm = new Hiring_Manager__c();
     hm.Name='HiringManager1';
     hm.Email_ID__c='raju@yahoo.com';
     hm.Contact_Number__c='7896541234';
     hm.Location__c='Hyderabad';
     insert hm;
     
     Position__c pos = new Position__c();
     pos.name='Position1';
     pos.Hiring_Manager__c=hm.Id;
     insert pos;
 
 } 

}